/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author uknow
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        keluar_login = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        tombol_login = new java.awt.Button();
        tombol_masuk_registrasi = new java.awt.Button();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 19, 255));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 239, 255));

        jLabel1.setFont(new java.awt.Font("URW Bookman L", 1, 40)); // NOI18N
        jLabel1.setText("THREE TICKET.COM");

        keluar_login.setBackground(new java.awt.Color(1, 1, 1));
        keluar_login.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        keluar_login.setForeground(new java.awt.Color(255, 0, 0));
        keluar_login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        keluar_login.setText("CLOSE");
        keluar_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                keluar_loginMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(255, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(204, 204, 204))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(keluar_login))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(keluar_login)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(21, 21, 21))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 900, 100);

        jPanel3.setBackground(new java.awt.Color(0, 77, 255));
        jPanel3.setLayout(null);

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        jLabel2.setText("Masukkan username dan password anda ");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(250, 10, 420, 24);

        jLabel3.setFont(new java.awt.Font("Fira Code SemiBold", 3, 15)); // NOI18N
        jLabel3.setText("Password ");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(270, 110, 90, 20);

        jLabel4.setFont(new java.awt.Font("Fira Code SemiBold", 3, 15)); // NOI18N
        jLabel4.setText("Username ");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(270, 60, 90, 20);

        jTextField2.setFont(new java.awt.Font("Fira Code SemiBold", 0, 15)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField2);
        jTextField2.setBounds(380, 50, 210, 30);

        jPasswordField1.setFont(new java.awt.Font("Fira Code SemiBold", 0, 15)); // NOI18N
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPanel3.add(jPasswordField1);
        jPasswordField1.setBounds(380, 100, 210, 30);

        tombol_login.setActionCommand("login");
        tombol_login.setBackground(new java.awt.Color(254, 254, 254));
        tombol_login.setLabel("LOGIN");
        tombol_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol_loginActionPerformed(evt);
            }
        });
        jPanel3.add(tombol_login);
        tombol_login.setBounds(460, 170, 60, 23);

        tombol_masuk_registrasi.setBackground(new java.awt.Color(254, 254, 254));
        tombol_masuk_registrasi.setLabel("REGISTRASI");
        tombol_masuk_registrasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol_masuk_registrasiActionPerformed(evt);
            }
        });
        jPanel3.add(tombol_masuk_registrasi);
        tombol_masuk_registrasi.setBounds(440, 230, 110, 23);

        jLabel5.setText("Belum mempunyai akun?");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(400, 200, 190, 18);

        jLabel6.setFont(new java.awt.Font("Noto Mono", 0, 12)); // NOI18N
        jLabel6.setText("Three Ticket.com adalah platform untuk pembelian ticket kereta api dengan desain yang menarik dan elegan untuk dipandang.");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(10, 360, 890, 30);

        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jPanel3.add(jLabel7);
        jLabel7.setBounds(300, 140, 380, 20);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 100, 900, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void tombol_masuk_registrasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol_masuk_registrasiActionPerformed
        // TODO add your handling code here:
        //masuk halaman registrasi
            registrasi rg=new registrasi();
            rg.setVisible(true);
            rg.pack();
            rg.setLocationRelativeTo(null);
            rg.setDefaultCloseOperation(login.EXIT_ON_CLOSE);
    }//GEN-LAST:event_tombol_masuk_registrasiActionPerformed

    private void keluar_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keluar_loginMouseClicked
        // TODO add your handling code here:
        // untuk keluar program
        System.exit(0);
    }//GEN-LAST:event_keluar_loginMouseClicked

    private void tombol_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol_loginActionPerformed
        // TODO add your handling code here:
        if(jPasswordField1.getText().equals(registrasi.password)&& (jTextField2.getText().equals(registrasi.username))){
            
            //masuk halaman tampilan_depan
            tampilan_depan td=new tampilan_depan();
            td.setVisible(true);
            td.pack();
            td.setLocationRelativeTo(null);
            td.setDefaultCloseOperation(registrasi.EXIT_ON_CLOSE);
        }
        else{
            jLabel7.setText("Username dan Password yang kamu masukkan salah!");
            
        }
    }//GEN-LAST:event_tombol_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel keluar_login;
    private java.awt.Button tombol_login;
    private java.awt.Button tombol_masuk_registrasi;
    // End of variables declaration//GEN-END:variables
}
