/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author uknow
 */
public class registrasi extends javax.swing.JFrame {

    /**
     * Creates new form registrasi
     */
    public static String username;
    public static String password;
    
    public registrasi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tombolkeluar = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        tombolregis = new java.awt.Button();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        masuk_login = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 239, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 100));

        jLabel1.setFont(new java.awt.Font("URW Bookman L", 1, 40)); // NOI18N
        jLabel1.setText("REGISTRASI");

        tombolkeluar.setBackground(new java.awt.Color(1, 1, 1));
        tombolkeluar.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        tombolkeluar.setForeground(new java.awt.Color(255, 0, 0));
        tombolkeluar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tombolkeluar.setText("CLOSE");
        tombolkeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tombolkeluarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(337, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(300, 300, 300))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tombolkeluar))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(tombolkeluar)
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 77, 255));
        jPanel3.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Fira Code SemiBold", 3, 15)); // NOI18N
        jLabel4.setText("Username ");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(280, 90, 90, 20);

        jTextField2.setFont(new java.awt.Font("Fira Code SemiBold", 0, 15)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField2);
        jTextField2.setBounds(480, 80, 210, 30);

        jLabel3.setFont(new java.awt.Font("Fira Code SemiBold", 3, 15)); // NOI18N
        jLabel3.setText("Re-type Password ");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(280, 190, 170, 20);

        jPasswordField1.setFont(new java.awt.Font("Fira Code SemiBold", 0, 15)); // NOI18N
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPanel3.add(jPasswordField1);
        jPasswordField1.setBounds(480, 180, 210, 30);

        jLabel5.setFont(new java.awt.Font("Fira Code SemiBold", 3, 15)); // NOI18N
        jLabel5.setText("Password ");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(280, 140, 90, 20);

        jPasswordField2.setFont(new java.awt.Font("Fira Code SemiBold", 0, 15)); // NOI18N
        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });
        jPanel3.add(jPasswordField2);
        jPasswordField2.setBounds(480, 130, 210, 30);

        tombolregis.setActionCommand("regis");
        tombolregis.setBackground(new java.awt.Color(254, 254, 254));
        tombolregis.setLabel("SUBMIT");
        tombolregis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolregisActionPerformed(evt);
            }
        });
        jPanel3.add(tombolregis);
        tombolregis.setBounds(560, 240, 60, 23);

        jLabel2.setFont(new java.awt.Font("Noto Mono", 0, 12)); // NOI18N
        jLabel2.setText("Jangan lupakan password anda, apabila perlu catat username dan password anda supaya tidak lupa.");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(10, 380, 890, 18);

        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jPanel3.add(jLabel6);
        jLabel6.setBounds(440, 220, 310, 20);

        jLabel7.setFont(new java.awt.Font("Fira Code SemiBold", 0, 15)); // NOI18N
        jLabel7.setText("Sudah Punya Akun?");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(280, 300, 160, 20);

        masuk_login.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        masuk_login.setText("MASUK");
        masuk_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masuk_loginActionPerformed(evt);
            }
        });
        jPanel3.add(masuk_login);
        masuk_login.setBounds(440, 300, 100, 28);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 402, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 96, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField2ActionPerformed

    private void tombolregisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolregisActionPerformed
        // TODO add your handling code here:
        // untuk cek password apakah sudah sama
        if(jPasswordField2.getText().equals(jPasswordField1.getText())){
            username=jTextField2.getText();
            password=jPasswordField2.getText();
            
            //masuk halaman login
            login lg=new login();
            lg.setVisible(true);
            lg.pack();
            lg.setLocationRelativeTo(null);
            lg.setDefaultCloseOperation(registrasi.EXIT_ON_CLOSE);
        
        }
        else{
            jLabel6.setText("Password yang kamu masukkan tidak sama");
    }//GEN-LAST:event_tombolregisActionPerformed
    }
    private void tombolkeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolkeluarMouseClicked
        // TODO add your handling code here:
        // untuk keluar program
        System.exit(0);
    }//GEN-LAST:event_tombolkeluarMouseClicked

    private void masuk_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masuk_loginActionPerformed
        // TODO add your handling code here:
        // untuk masuk ke login jika sudah punya akun
        //masuk halaman login
            login lg=new login();
            lg.setVisible(true);
            lg.pack();
            lg.setLocationRelativeTo(null);
            lg.setDefaultCloseOperation(registrasi.EXIT_ON_CLOSE);
        
    }//GEN-LAST:event_masuk_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registrasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JToggleButton masuk_login;
    private javax.swing.JLabel tombolkeluar;
    private java.awt.Button tombolregis;
    // End of variables declaration//GEN-END:variables
}
