/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author uknow
 */
public class tampilan_depan extends javax.swing.JFrame {

    /**
     * Creates new form tampilan_depan
     */
    public tampilan_depan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jam1 = new javax.swing.JRadioButton();
        jam14 = new javax.swing.JRadioButton();
        jam16 = new javax.swing.JRadioButton();
        jam5 = new javax.swing.JRadioButton();
        jam9 = new javax.swing.JRadioButton();
        jam13 = new javax.swing.JRadioButton();
        jumlahL = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jumlahT = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jumlahM = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jumlahS = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        bni = new javax.swing.JRadioButton();
        tunai = new javax.swing.JRadioButton();
        bri = new javax.swing.JRadioButton();
        bca = new javax.swing.JRadioButton();
        mandiri = new javax.swing.JRadioButton();
        dana = new javax.swing.JRadioButton();
        checkout = new java.awt.Button();
        jLabel10 = new javax.swing.JLabel();
        jam2 = new javax.swing.JRadioButton();
        jam6 = new javax.swing.JRadioButton();
        jam10 = new javax.swing.JRadioButton();
        jam3 = new javax.swing.JRadioButton();
        jam7 = new javax.swing.JRadioButton();
        jam11 = new javax.swing.JRadioButton();
        jam15 = new javax.swing.JRadioButton();
        jam4 = new javax.swing.JRadioButton();
        jam8 = new javax.swing.JRadioButton();
        jam12 = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        hasil_checkout = new javax.swing.JLabel();
        via = new javax.swing.JLabel();
        sentolo = new javax.swing.JComboBox<>();
        lempuyangan = new javax.swing.JComboBox<>();
        tugu = new javax.swing.JComboBox<>();
        maguwo = new javax.swing.JComboBox<>();
        hargaS = new javax.swing.JLabel();
        hargaL = new javax.swing.JLabel();
        hargaT = new javax.swing.JLabel();
        hargaM = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        ceklempuyangan = new javax.swing.JCheckBox();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        cekmaguwo = new javax.swing.JCheckBox();
        jPanel6 = new javax.swing.JPanel();
        cektugu = new javax.swing.JCheckBox();
        jPanel12 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cetak = new javax.swing.JToggleButton();
        jPanel7 = new javax.swing.JPanel();
        ceksentolo = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        keluar_tampilan_depan = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel3.setBackground(new java.awt.Color(0, 77, 255));
        jPanel3.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Noto Mono", 0, 12)); // NOI18N
        jLabel6.setText("Three Ticket.com adalah platform untuk pembelian ticket kereta api dengan desain yang menarik dan elegan untuk dipandang.");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(10, 370, 890, 30);

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 25)); // NOI18N
        jLabel2.setText("Jadwal Keberangkatan");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(330, 10, 280, 30);

        jam1.setBackground(new java.awt.Color(91, 91, 91));
        jam1.setText("10:00");
        jam1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jam1ActionPerformed(evt);
            }
        });
        jPanel3.add(jam1);
        jam1.setBounds(90, 90, 62, 23);

        jam14.setBackground(new java.awt.Color(91, 91, 91));
        jam14.setText("18:00");
        jPanel3.add(jam14);
        jam14.setBounds(660, 120, 123, 23);

        jam16.setBackground(new java.awt.Color(91, 91, 91));
        jam16.setText("20:00");
        jPanel3.add(jam16);
        jam16.setBounds(660, 180, 123, 23);

        jam5.setBackground(new java.awt.Color(91, 91, 91));
        jam5.setText("10:00");
        jPanel3.add(jam5);
        jam5.setBounds(280, 90, 123, 23);

        jam9.setBackground(new java.awt.Color(91, 91, 91));
        jam9.setText("10:00");
        jPanel3.add(jam9);
        jam9.setBounds(470, 90, 123, 23);

        jam13.setBackground(new java.awt.Color(91, 91, 91));
        jam13.setText("10:00");
        jPanel3.add(jam13);
        jam13.setBounds(660, 90, 123, 23);

        jumlahL.setFont(new java.awt.Font("Ubuntu Light", 1, 12)); // NOI18N
        jumlahL.setForeground(new java.awt.Color(1, 1, 1));
        jumlahL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahLActionPerformed(evt);
            }
        });
        jPanel3.add(jumlahL);
        jumlahL.setBounds(150, 210, 40, 30);

        jLabel4.setText("Jumlah");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(280, 220, 60, 18);

        jumlahT.setFont(new java.awt.Font("Ubuntu Light", 1, 12)); // NOI18N
        jumlahT.setForeground(new java.awt.Color(1, 1, 1));
        jumlahT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahTActionPerformed(evt);
            }
        });
        jPanel3.add(jumlahT);
        jumlahT.setBounds(340, 210, 40, 30);

        jLabel5.setText("Jumlah");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(470, 220, 60, 18);

        jumlahM.setFont(new java.awt.Font("Ubuntu Light", 1, 12)); // NOI18N
        jumlahM.setForeground(new java.awt.Color(1, 1, 1));
        jumlahM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahMActionPerformed(evt);
            }
        });
        jPanel3.add(jumlahM);
        jumlahM.setBounds(530, 210, 40, 30);

        jLabel7.setText("Jumlah");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(660, 220, 60, 18);

        jumlahS.setFont(new java.awt.Font("Ubuntu Light", 1, 12)); // NOI18N
        jumlahS.setForeground(new java.awt.Color(1, 1, 1));
        jumlahS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahSActionPerformed(evt);
            }
        });
        jPanel3.add(jumlahS);
        jumlahS.setBounds(720, 210, 40, 30);

        jLabel8.setBackground(new java.awt.Color(254, 254, 254));
        jLabel8.setFont(new java.awt.Font("Serif", 1, 20)); // NOI18N
        jLabel8.setText("VIA");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(680, 300, 50, 24);

        bni.setBackground(new java.awt.Color(0, 77, 255));
        bni.setText("Debit BNI");
        bni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bniActionPerformed(evt);
            }
        });
        jPanel3.add(bni);
        bni.setBounds(140, 350, 100, 23);

        tunai.setBackground(new java.awt.Color(0, 77, 255));
        tunai.setText("Tunai");
        tunai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tunaiActionPerformed(evt);
            }
        });
        jPanel3.add(tunai);
        tunai.setBounds(10, 320, 80, 23);

        bri.setBackground(new java.awt.Color(0, 77, 255));
        bri.setText("Debit BRI");
        jPanel3.add(bri);
        bri.setBounds(140, 320, 100, 23);

        bca.setBackground(new java.awt.Color(0, 77, 255));
        bca.setText("Debit BCA");
        jPanel3.add(bca);
        bca.setBounds(240, 320, 100, 23);

        mandiri.setBackground(new java.awt.Color(0, 77, 255));
        mandiri.setText("Debit Mandiri");
        mandiri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mandiriActionPerformed(evt);
            }
        });
        jPanel3.add(mandiri);
        mandiri.setBounds(10, 350, 130, 23);

        dana.setBackground(new java.awt.Color(0, 77, 255));
        dana.setText("DANA");
        jPanel3.add(dana);
        dana.setBounds(240, 350, 80, 23);

        checkout.setActionCommand("total");
        checkout.setBackground(new java.awt.Color(254, 254, 254));
        checkout.setLabel("Checkout");
        checkout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkoutMouseClicked(evt);
            }
        });
        checkout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutActionPerformed(evt);
            }
        });
        jPanel3.add(checkout);
        checkout.setBounds(440, 300, 70, 23);

        jLabel10.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("TOTAL");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(400, 340, 60, 20);

        jam2.setBackground(new java.awt.Color(91, 91, 91));
        jam2.setText("18:00");
        jPanel3.add(jam2);
        jam2.setBounds(90, 120, 123, 23);

        jam6.setBackground(new java.awt.Color(91, 91, 91));
        jam6.setText("18:00");
        jPanel3.add(jam6);
        jam6.setBounds(280, 120, 123, 23);

        jam10.setBackground(new java.awt.Color(91, 91, 91));
        jam10.setText("18:00");
        jPanel3.add(jam10);
        jam10.setBounds(470, 120, 123, 23);

        jam3.setBackground(new java.awt.Color(91, 91, 91));
        jam3.setText("15:00");
        jPanel3.add(jam3);
        jam3.setBounds(90, 150, 123, 23);

        jam7.setBackground(new java.awt.Color(91, 91, 91));
        jam7.setText("15:00");
        jPanel3.add(jam7);
        jam7.setBounds(280, 150, 123, 23);

        jam11.setBackground(new java.awt.Color(91, 91, 91));
        jam11.setText("15:00");
        jPanel3.add(jam11);
        jam11.setBounds(470, 150, 123, 23);

        jam15.setBackground(new java.awt.Color(91, 91, 91));
        jam15.setText("15:00");
        jPanel3.add(jam15);
        jam15.setBounds(660, 150, 123, 23);

        jam4.setBackground(new java.awt.Color(91, 91, 91));
        jam4.setText("20:00");
        jPanel3.add(jam4);
        jam4.setBounds(90, 180, 123, 23);

        jam8.setBackground(new java.awt.Color(91, 91, 91));
        jam8.setText("20:00");
        jPanel3.add(jam8);
        jam8.setBounds(280, 180, 123, 23);

        jam12.setBackground(new java.awt.Color(91, 91, 91));
        jam12.setText("20:00");
        jPanel3.add(jam12);
        jam12.setBounds(470, 180, 123, 23);

        jLabel12.setFont(new java.awt.Font("Serif", 1, 20)); // NOI18N
        jLabel12.setText("Metode Pembayaran");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(10, 290, 230, 24);

        hasil_checkout.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        hasil_checkout.setForeground(new java.awt.Color(255, 0, 0));
        hasil_checkout.setText("Rp 0");
        jPanel3.add(hasil_checkout);
        hasil_checkout.setBounds(470, 340, 120, 20);

        via.setBackground(new java.awt.Color(0, 77, 255));
        via.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        via.setForeground(new java.awt.Color(255, 0, 0));
        jPanel3.add(via);
        via.setBounds(650, 340, 140, 20);

        sentolo.setBackground(new java.awt.Color(156, 156, 156));
        sentolo.setForeground(new java.awt.Color(1, 1, 1));
        sentolo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Kereta", "Jaka Tingkir", "Fajar Utama", "Senja Utama", "KRL" }));
        sentolo.setName(""); // NOI18N
        sentolo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sentoloActionPerformed(evt);
            }
        });
        jPanel3.add(sentolo);
        sentolo.setBounds(660, 240, 140, 20);

        lempuyangan.setBackground(new java.awt.Color(156, 156, 156));
        lempuyangan.setForeground(new java.awt.Color(1, 1, 1));
        lempuyangan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Kereta", "Jaka Tingkir", "Fajar Utama", "Senja Utama", "KRL" }));
        lempuyangan.setName(""); // NOI18N
        lempuyangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lempuyanganActionPerformed(evt);
            }
        });
        jPanel3.add(lempuyangan);
        lempuyangan.setBounds(90, 240, 140, 20);

        tugu.setBackground(new java.awt.Color(156, 156, 156));
        tugu.setForeground(new java.awt.Color(1, 1, 1));
        tugu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Kereta", "Jaka Tingkir", "Fajar Utama", "Senja Utama", "KRL" }));
        tugu.setName(""); // NOI18N
        tugu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tuguActionPerformed(evt);
            }
        });
        jPanel3.add(tugu);
        tugu.setBounds(280, 240, 140, 20);

        maguwo.setBackground(new java.awt.Color(156, 156, 156));
        maguwo.setForeground(new java.awt.Color(1, 1, 1));
        maguwo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Kereta", "Jaka Tingkir", "Fajar Utama", "Senja Utama", "KRL" }));
        maguwo.setName(""); // NOI18N
        maguwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maguwoActionPerformed(evt);
            }
        });
        jPanel3.add(maguwo);
        maguwo.setBounds(470, 240, 140, 20);
        jPanel3.add(hargaS);
        hargaS.setBounds(690, 270, 140, 20);
        jPanel3.add(hargaL);
        hargaL.setBounds(120, 270, 140, 20);
        jPanel3.add(hargaT);
        hargaT.setBounds(310, 270, 140, 20);
        jPanel3.add(hargaM);
        hargaM.setBounds(500, 270, 140, 20);

        jPanel4.setBackground(new java.awt.Color(0, 255, 3));
        jPanel4.setForeground(new java.awt.Color(1, 1, 1));

        ceklempuyangan.setBackground(new java.awt.Color(0, 255, 3));
        ceklempuyangan.setForeground(new java.awt.Color(1, 1, 1));
        ceklempuyangan.setText("Stasiun Lempuyangan");
        ceklempuyangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceklempuyanganActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ceklempuyangan, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ceklempuyangan)
        );

        jPanel3.add(jPanel4);
        jPanel4.setBounds(90, 60, 180, 20);

        jPanel9.setBackground(new java.awt.Color(91, 91, 91));

        jLabel3.setText("Jumlah");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 120, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(138, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(34, 34, 34))
        );

        jPanel3.add(jPanel9);
        jPanel9.setBounds(90, 80, 180, 190);

        jPanel10.setBackground(new java.awt.Color(91, 91, 91));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel10);
        jPanel10.setBounds(280, 80, 180, 190);

        jPanel11.setBackground(new java.awt.Color(91, 91, 91));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel11);
        jPanel11.setBounds(470, 80, 180, 190);

        jPanel5.setBackground(new java.awt.Color(0, 255, 3));
        jPanel5.setForeground(new java.awt.Color(1, 1, 1));

        cekmaguwo.setBackground(new java.awt.Color(0, 255, 3));
        cekmaguwo.setForeground(new java.awt.Color(1, 1, 1));
        cekmaguwo.setText("Stasiun Maguwo");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(cekmaguwo, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 28, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cekmaguwo))
        );

        jPanel3.add(jPanel5);
        jPanel5.setBounds(470, 60, 180, 23);

        jPanel6.setBackground(new java.awt.Color(0, 255, 3));
        jPanel6.setForeground(new java.awt.Color(1, 1, 1));

        cektugu.setBackground(new java.awt.Color(0, 255, 3));
        cektugu.setForeground(new java.awt.Color(1, 1, 1));
        cektugu.setText("Stasiun Tugu");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(cektugu, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 50, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cektugu))
        );

        jPanel3.add(jPanel6);
        jPanel6.setBounds(280, 60, 180, 23);

        jPanel12.setBackground(new java.awt.Color(91, 91, 91));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel12);
        jPanel12.setBounds(660, 80, 180, 190);

        jLabel9.setText("Rp");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(660, 270, 49, 18);

        jLabel11.setText("Rp");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(90, 270, 40, 18);

        jLabel13.setText("Rp");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(280, 270, 49, 18);

        jLabel14.setText("Rp");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(470, 270, 49, 18);

        cetak.setText("CETAK");
        cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetakActionPerformed(evt);
            }
        });
        jPanel3.add(cetak);
        cetak.setBounds(790, 20, 110, 28);

        jPanel7.setBackground(new java.awt.Color(0, 255, 3));
        jPanel7.setForeground(new java.awt.Color(1, 1, 1));

        ceksentolo.setBackground(new java.awt.Color(0, 255, 3));
        ceksentolo.setForeground(new java.awt.Color(1, 1, 1));
        ceksentolo.setText("Stasiun Sentolo");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(ceksentolo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 30, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ceksentolo))
        );

        jPanel3.add(jPanel7);
        jPanel7.setBounds(660, 60, 180, 23);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 100, 910, 400);

        jPanel2.setBackground(new java.awt.Color(0, 239, 255));

        keluar_tampilan_depan.setBackground(new java.awt.Color(1, 1, 1));
        keluar_tampilan_depan.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        keluar_tampilan_depan.setForeground(new java.awt.Color(255, 0, 0));
        keluar_tampilan_depan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        keluar_tampilan_depan.setText("CLOSE");
        keluar_tampilan_depan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                keluar_tampilan_depanMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("URW Bookman L", 1, 40)); // NOI18N
        jLabel1.setText("THREE TICKET.COM");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(251, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                .addComponent(keluar_tampilan_depan))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(keluar_tampilan_depan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 910, 100);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jumlahLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahLActionPerformed

    private void jumlahTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahTActionPerformed

    private void jumlahMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahMActionPerformed

    private void jumlahSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahSActionPerformed

    private void bniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bniActionPerformed

    private void checkoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutActionPerformed
        // TODO add your handling code here:
        
        if(ceklempuyangan.isSelected()){
        //memunculkan hasil pembelian tiket lempuyangan
        int JumlahBeliL=Integer.parseInt(jumlahL.getText());
        int HargaTiketL=Integer.parseInt(hargaL.getText());
        int tot1=HargaTiketL*JumlahBeliL;
        hasil_checkout.setText("Rp "+tot1);  
        }
        if(cektugu.isSelected()){
        //memunculkan hasil pembelian tiket tugu
        int JumlahBeliT=Integer.parseInt(jumlahT.getText());
        int HargaTiketT=Integer.parseInt(hargaT.getText());
        int tot2=HargaTiketT*JumlahBeliT;
        hasil_checkout.setText("Rp "+tot2);
        }
        if(cekmaguwo.isSelected()){
        //memunculkan hasil pembelian tiket maguwo
        int JumlahBeliM=Integer.parseInt(jumlahM.getText());
        int HargaTiketM=Integer.parseInt(hargaM.getText());
        int tot3=HargaTiketM*JumlahBeliM;
        hasil_checkout.setText("Rp "+tot3);
        }
        if(ceksentolo.isSelected()){
        //memunculkan hasil pembelian tiket sentolo
        int JumlahBeliS=Integer.parseInt(jumlahS.getText());
        int HargaTiketS=Integer.parseInt(hargaS.getText());
        int tot4=HargaTiketS*JumlahBeliS;
        hasil_checkout.setText("Rp "+tot4);
        }   
        
        // jika metode tunai dipilih maka pada via akan tampil metode pembayaran yang dipilih
        if(tunai.isSelected())
            via.setText(tunai.getActionCommand());
        if(mandiri.isSelected())
            via.setText(mandiri.getActionCommand());
        if(bca.isSelected())
            via.setText(bca.getActionCommand());
        if(bri.isSelected())
            via.setText(bri.getActionCommand());
        if(dana.isSelected())
            via.setText(dana.getActionCommand());
        if(bni.isSelected())
            via.setText(bni.getActionCommand());
        
    }//GEN-LAST:event_checkoutActionPerformed

    private void keluar_tampilan_depanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keluar_tampilan_depanMouseClicked
        // TODO add your handling code here:
        // untuk keluar program
        System.exit(0);
    }//GEN-LAST:event_keluar_tampilan_depanMouseClicked

    private void lempuyanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lempuyanganActionPerformed
        // TODO add your handling code here:
        // setting harga dari tiap kereta
        String nama_keretaL=(String)lempuyangan.getSelectedItem();
        switch (nama_keretaL){
            case "Jaka Tingkir":
                hargaL.setText("50000");
                break;
            case "Fajar Utama":
                hargaL.setText("100000");
                break;
            case "Senja Utama":
                hargaL.setText("80000");
                break; 
            case "KRL":
                hargaL.setText("10000");
                break;
        }
    }//GEN-LAST:event_lempuyanganActionPerformed

    private void mandiriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mandiriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mandiriActionPerformed

    private void checkoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkoutMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_checkoutMouseClicked

    private void tuguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tuguActionPerformed
        // TODO add your handling code here:
        String nama_keretaT=(String)tugu.getSelectedItem();
        switch (nama_keretaT){
            case "Jaka Tingkir":
                hargaT.setText("40000");
                break;
            case "Fajar Utama":
                hargaT.setText("90000");
                break;
            case "Senja Utama":
                hargaT.setText("70000");
                break; 
            case "KRL":
                hargaT.setText("12000");
                break;
        }
    }//GEN-LAST:event_tuguActionPerformed

    private void maguwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maguwoActionPerformed
        // TODO add your handling code here:
        // setting harga dari tiap kereta
        String nama_keretaM=(String)maguwo.getSelectedItem();
        switch (nama_keretaM){
            case "Jaka Tingkir":
                hargaM.setText("80000");
                break;
            case "Fajar Utama":
                hargaM.setText("70000");
                break;
            case "Senja Utama":
                hargaM.setText("120000");
                break; 
            case "KRL":
                hargaM.setText("15000");
                break;
        }
    }//GEN-LAST:event_maguwoActionPerformed

    private void sentoloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sentoloActionPerformed
        // TODO add your handling code here:
        // setting harga dari tiap kereta
        String nama_keretaS=(String)sentolo.getSelectedItem();
        switch (nama_keretaS){
            case "Jaka Tingkir":
                hargaS.setText("100000");
                break;
            case "Fajar Utama":
                hargaS.setText("120000");
                break;
            case "Senja Utama":
                hargaS.setText("90000");
                break; 
            case "KRL":
                hargaS.setText("8000");
                break;
        }
    }//GEN-LAST:event_sentoloActionPerformed

    private void tunaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tunaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tunaiActionPerformed

    private void ceklempuyanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ceklempuyanganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ceklempuyanganActionPerformed

    private void cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetakActionPerformed
        // TODO add your handling code here:
        //masuk halaman cetak
            cetaktiket ct=new cetaktiket();
            ct.setVisible(true);
            ct.pack();
            ct.setLocationRelativeTo(null);
            ct.setDefaultCloseOperation(tampilan_depan.EXIT_ON_CLOSE);
    }//GEN-LAST:event_cetakActionPerformed

    private void jam1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jam1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jam1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tampilan_depan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tampilan_depan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tampilan_depan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tampilan_depan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tampilan_depan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JRadioButton bca;
    public static javax.swing.JRadioButton bni;
    public static javax.swing.JRadioButton bri;
    public static javax.swing.JCheckBox ceklempuyangan;
    public static javax.swing.JCheckBox cekmaguwo;
    public static javax.swing.JCheckBox ceksentolo;
    public static javax.swing.JCheckBox cektugu;
    private javax.swing.JToggleButton cetak;
    public static java.awt.Button checkout;
    public static javax.swing.JRadioButton dana;
    private javax.swing.JLabel hargaL;
    private javax.swing.JLabel hargaM;
    private javax.swing.JLabel hargaS;
    private javax.swing.JLabel hargaT;
    public static javax.swing.JLabel hasil_checkout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    public static javax.swing.JRadioButton jam1;
    public static javax.swing.JRadioButton jam10;
    public static javax.swing.JRadioButton jam11;
    public static javax.swing.JRadioButton jam12;
    public static javax.swing.JRadioButton jam13;
    public static javax.swing.JRadioButton jam14;
    public static javax.swing.JRadioButton jam15;
    public static javax.swing.JRadioButton jam16;
    public static javax.swing.JRadioButton jam2;
    public static javax.swing.JRadioButton jam3;
    public static javax.swing.JRadioButton jam4;
    public static javax.swing.JRadioButton jam5;
    public static javax.swing.JRadioButton jam6;
    public static javax.swing.JRadioButton jam7;
    public static javax.swing.JRadioButton jam8;
    public static javax.swing.JRadioButton jam9;
    private javax.swing.JTextField jumlahL;
    private javax.swing.JTextField jumlahM;
    private javax.swing.JTextField jumlahS;
    private javax.swing.JTextField jumlahT;
    private javax.swing.JLabel keluar_tampilan_depan;
    public static javax.swing.JComboBox<String> lempuyangan;
    public static javax.swing.JComboBox<String> maguwo;
    public static javax.swing.JRadioButton mandiri;
    public static javax.swing.JComboBox<String> sentolo;
    public static javax.swing.JComboBox<String> tugu;
    public static javax.swing.JRadioButton tunai;
    private javax.swing.JLabel via;
    // End of variables declaration//GEN-END:variables
}
